project_id = "agenda-profissional"

[api]
enabled = true
port = 56021
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 56022
shadow_port = 56020
major_version = 15

[studio]
enabled = true
port = 56023

[inbucket]
enabled = true
port = 56024

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/**", "io.supabase.flutter://login-callback"]
jwt_expiry = 3600
enable_signup = true

[edge_runtime]
enabled = true
policy = "per_worker"
inspector_port = 56083

[analytics]
enabled = false

[functions.bootstrap-tenant]
verify_jwt = true

[functions.create-appointment]
verify_jwt = true
